language: python

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows

#python: 
# - "3.7.4"

#before_install:
# - git clone https://github.com/TravisToolbox/pycodestyle-travis.git

#install:
# - ./pycodestyle-travis/install.sh

script:
 - export VERSION=$(git describe --tags --abbrev=1 | sed -E 's|-(.*)-.*|.\1|g')
 - echo "__version__ = \"$VERSION\"" > rfapi-red/_version.py
 - ls
 #- ./pycodestyle-travis/scan.sh
 #- python3 -m nose --with-doctest rfapi
 #- python setup.py sdist bdist_wheel
 #- python3 -m twine upload -u @token -p $PYPI_TOKEN --repository-url https://test.pypi.org/legacy/ dist/*

deploy:
 - provider: pypi
   user: __token__
   password: $PYPI_TOKEN
   server: https://test.pypi.org/legacy/
   distributions: "sdist bdist_wheel"
   skip_cleanup: true
   on:
     branch: master
     tags: true
