language: python

matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      env: RUNPYLINT=true
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7.16
      env: RUNPYLINT=false

#python: 
# - "3.7.4"

#before_install:
# - git clone https://github.com/TravisToolbox/pycodestyle-travis.git

install:
 - pip install -r requirements.txt
 - pip install -r test_requirements.txt
# - ./pycodestyle-travis/install.sh


script:
 - export VERSION=$(git describe --tags --abbrev=1 | sed -E 's|-(.*)-.*|.\1|g')
 - echo "__version__ = \"$VERSION\"" > rfapi/_version.py
 #- ./pycodestyle-travis/scan.sh
 # Run pylint, terminate if it has any errors
 #- pylint -E rfapi
 # - (($RUNPYLINT == true && pylint -E rfapi) || ($RUNPYLINT == false)) || travis_terminate 1
 # Run Tests on both python2 & 3
 - (python3 -m nose --with-doctest rfapi || python2 -m nose --with-doctest rfapi) || travis_terminate 1

before_deploy:
 - export VERSION=$(git describe --tags --abbrev=1 | sed -E 's|-(.*)-.*|.\1|g')
 - echo "__version__ = \"$VERSION\"" > rfapi/_version.py

deploy:
 - provider: pypi
   user: __token__
   password: $PYPI_TOKEN
   server: https://test.pypi.org/legacy/
   distributions: "sdist bdist_wheel"
   skip_cleanup: true
   on:
     branch: master
     tags: true
