language: python

matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      env: 
        FAIL_BUILD_ON_PYLINT_ERRORS="true"
        DEPLOY=true
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7.16
      env: 
        DEPLOY=false

#python: 
# - "3.7.4"

install:
 - pip install -r requirements.txt
 - pip install -r test_requirements.txt

before_script:
 - export VERSION=$(git describe --tags --abbrev=1 | sed -E 's|-(.*)-.*|.\1|g')
 - echo "__version__ = \"$VERSION\"" > rfapi/_version.py

script:
 # Run pylint, terminate if it has any errors
 - if [ "$FAIL_BUILD_ON_PYLINT_ERRORS" == "true" ]; then
     pylint -E rfapi || travis_terminate 1;
   else
     pylint -E rfapi;
   fi
 # Run Tests 
 # - python -m nose --with-doctest rfapi || travis_terminate 1
 #
 # NOT WORKING
 #- ./pycodestyle-travis/scan.sh

before_deploy:
 - export VERSION=$(git describe --tags --abbrev=1 | sed -E 's|-(.*)-.*|.\1|g')
 - echo "__version__ = \"$VERSION\"" > rfapi/_version.py
 - python setup.py build sdist

deploy:
# - provider: pypi
#   user: __token__
#   password: $PYPI_TOKEN
#   server: https://test.pypi.org/legacy/
#   distributions: "sdist bdist_wheel"
#   skip_cleanup: true
#   on:
#     condition: $DEPLOY = true
#     branch: master
#     tags: true
#  - provider: releases
#    api_key: "$GITHUB_OAUTH_TOKEN"
#    file: "dist/rfapi-$VERSION.tar.gz"
#    skip_cleanup: true
#    on:
#      tags: true
#      condition: $DEPLOY = true
